app/fund/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField
from wtforms.validators import DataRequired,Length,Optional
class QueryFund(FlaskForm):
    code = StringField('Fund info',validators=[DataRequired(),Length(6,10)])
    search = SubmitField('search')


class QueryCB(FlaskForm):
    cb_code = StringField('CB info',validators=[DataRequired()])
    search_bt1 = SubmitField('search')


class UpdateCBCode(FlaskForm):
    update_bt = SubmitField('Update code')

app/jingzhi/forms.py
# -*-coding=utf-8-*-

# @Time : 2020/3/11 15:39
# @File : forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,DecimalField,FloatField,BooleanField
from wtforms.validators import DataRequired,Length,Optional

class QueryJZ(FlaskForm):

    submit1 = SubmitField('show jz')

class UpdateJZ(FlaskForm):

    money = FloatField('money',validators=[DataRequired()])
    change = FloatField('change',validators=[Optional()])
    submit2 = SubmitField('update')

app/fund/__init__.py
from flask import Blueprint
# from . import views Can't import this before Bluepriint

fund = Blueprint('fund',__name__)
from . import views # must import this line

app/fund/views.py
import json

from . import fund
from flask import jsonify, render_template,flash
from .forms import QueryFund, QueryCB, UpdateCBCode
from .function import fetch,update_cb_code_fun
import tushare as ts

try:
    conn = ts.get_apis()
except Exception as e:
    conn = None


# TODO mapping code and name as dict
try:
    f=open('codes.cfg','r')
    code_dict = json.load(f)
except Exception as e:

    code_dict=None

@fund.route('fund', methods=['GET', 'POST'])
def fund_info():
    form_fund = QueryFund()
    form_cb = QueryCB()
    form_update_cb_code = UpdateCBCode()

    if form_fund.search.data and form_fund.validate_on_submit():

        code = form_fund.code.data
        name, price, percent = fetch(code)
        return render_template('fund.html',
                               form_fund=form_fund,
                               form_cb=form_cb,
                               form_update_cb_code=form_update_cb_code,

                               price=price,
                               name=name,
                               percent=percent)

    elif form_cb.search_bt1.data and form_cb.validate_on_submit():
        text = form_cb.cb_code.data
        bond_id_list = code_dict.get(text)
        bond_name_dict = {}

        if text.isdigit():
            bond_list=[text]
            for item in bond_list:
                k=list(item.keys())[0]
                bond_list.append(k)
                v = list(item.values())[0]
                bond_name_dict[k]=v
        else:
            # pinyin
            if bond_id_list is None:
                flash('No dict found!')
                return render_template('fund.html',
                                       form_fund=form_fund,
                                       form_cb=form_cb,
                                       form_update_cb_code=form_update_cb_code,
                                       cb_percent='',
                                       cb_price='',
                                       ask1='',
                                       bid1='',
                                       diff=''
                                       )
            bond_list=[]
            for item in bond_id_list:
                k=list(item.keys())[0]
                bond_list.append(k)
                v = list(item.values())[0]
                bond_name_dict[k]=v
        try:
            df = ts.quotes(bond_list, conn=conn)
        except Exception as e:
            print(e)
            return render_template('fund.html',
                                   form_fund=form_fund,
                                   form_cb=form_cb,
                                   form_update_cb_code=form_update_cb_code,
                                   cb_percent='',
                                   cb_price='',
                                   ask1='',
                                   bid1='',
                                   diff=''
                                   )
        result_list=[]
        for index,row in df.iterrows():
            last_close = row['last_close'] / 10
            cb_price = round(row['price'] / 10, 1)
            cb_percent = round((cb_price - last_close) / last_close * 100, 1)
            ask1 = row['ask1']
            bid1 = row['bid1']
            try:
                diff = round((ask1 - bid1) / bid1 * 100, 1)
            except:
                diff = 0
            d={}
            d['cb_price']=cb_price
            d['cb_percent']=cb_percent
            d['ask1']=round(ask1/10,1)
            d['bid1']=round(bid1/10,1)
            d['diff']=diff
            d['bond_name']=bond_name_dict.get(row['code']).replace('转债','')
            result_list.append(d)
        return render_template('fund.html',
                               form_fund=form_fund,
                               form_cb=form_cb,
                               form_update_cb_code=form_update_cb_code,
                               bond_lists=result_list
                               )
    elif form_update_cb_code.update_bt.data and form_update_cb_code.validate_on_submit():
            # 更新代码
            result = update_cb_code_fun()
            # print('updating coding')
            with open('codes.cfg','w') as f:
                json.dump(result,f,ensure_ascii=False)
            flash('Update code succussfully!')
            return render_template('fund.html',
                                   form_fund=form_fund,
                                   form_cb=form_cb,
                                   form_update_cb_code=form_update_cb_code,
                                   )


    else:
        return render_template('fund.html',
                               form_fund=form_fund,
                               form_cb=form_cb,
                               form_update_cb_code=form_update_cb_code
                               )

app/jingzhi/__init__.py
# -*-coding=utf-8-*-

# @Time : 2020/3/11 15:27
# @File : __init__.py.py
from flask import Blueprint
jingzhi = Blueprint('jingzhi',__name__)
from . import views

app/jingzhi/views.py
# -*-coding=utf-8-*-

# @Time : 2020/3/11 15:28
# @File : views.py
import datetime
import tushare as ts
from . import jingzhi
import pymysql
from flask import request,render_template,flash
from .forms import QueryJZ,UpdateJZ
# from .function import cursor,con
from config import DB_PASSWORD,DB_HOST,DB_PORT,DB_USER
GJ_BASE=1000

LABELS=['Date','Assert','Change','NetValue','NetValuePercent','Share','Profit','HS300']
HS_START=4138.51

@jingzhi.route('gj_info',methods=['GET','POST'])
def gj_info():

    update_form = UpdateJZ()
    query_form = QueryJZ()
    stock_type='GJ'
    if request.method=='GET':
        return render_template('jingzhi.html',query_form =query_form,update_form=update_form,stock_type=stock_type)

    else:
        con = pymysql.connect(host=DB_HOST, port=DB_PORT, user=DB_USER, password=DB_PASSWORD, db='db_stock',
                              cursorclass=pymysql.cursors.DictCursor)
        cursor = con.cursor()

        if query_form.submit1.data and query_form.validate_on_submit():
            print('query_form')
            sql='select * from tb_jingzhi_gj_flask'
            cursor.execute(sql)
            ret=cursor.fetchall()
            content_list=[]
            for item in ret:
                date=item.get(LABELS[0]).strftime('%Y-%m-%d')
                Assert=int(item.get(LABELS[1]))
                Change=int(item.get(LABELS[2]))
                netvalue=item.get(LABELS[3])
                netvaluepercent=item.get(LABELS[4])
                share=int(item.get(LABELS[5]))
                profit=int(item.get(LABELS[6]))
                hs300=item.get(LABELS[7])
                content_list.append([date,Assert,Change,netvalue,netvaluepercent,share,profit,hs300])
            content_list=content_list[::-1]
            return render_template('jingzhi.html',stock_type=stock_type,query_form =query_form,update_form=update_form,labels=LABELS,content=content_list)

        elif update_form.submit2.data and update_form.validate_on_submit():
            df = ts.get_index()
            current_v = df[df['code'] == '000300']['close'].values[0]
            hs_latest = round(float(current_v) / HS_START, 2)

            change = update_form.change.data
            money=update_form.money.data
            # change 有正和负
            if change is None:

                change=0


            sql = 'select * from tb_jingzhi_gj_flask order by id desc limit 1'
            cursor.execute(sql)
            ret=cursor.fetchone()
            last_netvalue= ret.get('NetValue')
            last_assert= ret.get('Assert')
            share= ret.get('Share')

            change_share = int(change*last_netvalue)
            new_share = share+change_share
            latest_net = round(money/new_share,4)
            net_value_diff_p = round((latest_net-last_netvalue)/last_netvalue*100,2)
            new_profit=money-last_assert-change
            print(datetime.datetime.now(),money,change,last_netvalue,net_value_diff_p,new_share,new_profit,hs_latest)
            update_sql = 'insert into `tb_jingzhi_gj_flask` (`Date`,`Assert`,`Change`,`NetValue`,`NetValuePercent`,`Share`,`Profit`,`HS300`) VALUES(%s,%s,%s,%s,%s,%s,%s,%s)'
            cursor.execute(update_sql,(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),money,change,latest_net,net_value_diff_p,new_share,new_profit,hs_latest))
            try:
                con.commit()
            except Exception as e:
                print(e)
                con.rollback()
            else:
                print('update successfully')
                # con.close()
                # 使用flash提醒
                flash('update jz in db!')
            return render_template('jingzhi.html',stock_type=stock_type,query_form =query_form,update_form=update_form)

@jingzhi.route('hb_info',methods=['GET','POST'])
def hb_info():

    update_form = UpdateJZ()
    query_form = QueryJZ()
    stock_type='HB'
    if request.method=='GET':
        return render_template('jingzhi.html',query_form =query_form,update_form=update_form,stock_type=stock_type)

    else:
        con = pymysql.connect(host=DB_HOST, port=DB_PORT, user=DB_USER, password=DB_PASSWORD, db='db_stock',
                              cursorclass=pymysql.cursors.DictCursor)
        cursor = con.cursor()
        if query_form.submit1.data and query_form.validate_on_submit():
            sql='select * from tb_jingzhi_hb_flask'
            cursor.execute(sql)
            ret=cursor.fetchall()
            content_list=[]
            for item in ret:
                date=item.get(LABELS[0]).strftime('%Y-%m-%d')
                Assert=int(item.get(LABELS[1]))
                Change=int(item.get(LABELS[2]))
                netvalue=item.get(LABELS[3])
                netvaluepercent=item.get(LABELS[4])
                share=int(item.get(LABELS[5]))
                profit=int(item.get(LABELS[6]))
                hs300=item.get(LABELS[7])
                content_list.append([date,Assert,Change,netvalue,netvaluepercent,share,profit,hs300])
            content_list=content_list[::-1]
            return render_template('jingzhi.html',stock_type=stock_type,query_form =query_form,update_form=update_form,labels=LABELS,content=content_list)

        elif update_form.submit2.data and update_form.validate_on_submit():
            df = ts.get_index()
            current_v = df[df['code'] == '000300']['close'].values[0]
            hs_latest = round(float(current_v) / HS_START, 2)

            change = update_form.change.data
            money=update_form.money.data
            # change 有正和负
            if change is None:

                change=0


            sql = 'select * from tb_jingzhi_hb_flask order by id desc limit 1'
            cursor.execute(sql)
            ret=cursor.fetchone()
            last_netvalue= ret.get('NetValue')
            last_assert= ret.get('Assert')
            share= ret.get('Share')

            change_share = int(change*last_netvalue)
            new_share = share+change_share
            latest_net = round(money/new_share,4)
            net_value_diff = latest_net-last_netvalue
            net_value_diff_p = round((latest_net-last_netvalue)/last_netvalue*100,2)
            new_profit=money-last_assert-change
            # print(datetime.datetime.now(),money,change,last_netvalue,net_value_diff_p,new_share,new_profit,hs_latest)
            update_sql = 'insert into `tb_jingzhi_hb_flask` (`Date`,`Assert`,`Change`,`NetValue`,`NetValuePercent`,`Share`,`Profit`,`HS300`) VALUES(%s,%s,%s,%s,%s,%s,%s,%s)'
            cursor.execute(update_sql,(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),money,change,latest_net,net_value_diff_p,new_share,new_profit,hs_latest))
            try:
                con.commit()
            except Exception as e:
                print(e)
                con.rollback()
            else:
                print('update successfully')
                # con.close()
                flash('update jz in db!')

            return render_template('jingzhi.html',stock_type=stock_type,query_form =query_form,update_form=update_form)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}ManageMent{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Wealth</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('fund.fund_info') }}">fund cb</a></li>
            </ul>

            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('cb.get_cb_list') }}">cb list</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('jingzhi.gj_info') }}">gj jing zhi</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('jingzhi.hb_info') }}">hb jing zhi</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('realtime.monitor') }}">realtime</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/cb_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Management{% endblock %}

{% block page_content %}
<div>
    <h1>CB List</h1>
</div>
<div>
    {{ wtf.quick_form(form) }}

</div>
<div class="panel-body">
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                {% for i in labels %}
                <td>{{ i }}</td>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for i in content %}
            <tr>
                {% for j in i %}
                <td>{{ j }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
            </tbody>

        </table>
        <div>共{{ total }}个</div>
    </div>
</div>
{% endblock %}

app/templates/fund.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Management{% endblock %}

{% block page_content %}
{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}

<h1>search engine</h1>
<div>
    {{ wtf.quick_form(form_fund) }}
</div>

<div>{{ name }} : {{ price }} percent : {{ percent }}%</div>

<br>
<br>
<br>
======================================================
<br>
<br>
<br>
{{ wtf.quick_form(form_update_cb_code) }}
<br>
<realtime>
{{ wtf.quick_form(form_cb) }}
<br>
{% for item in bond_lists %}
<ul>
    <h4>{{ item.bond_name }}</h4>
<p>realtime : {{ item.cb_price }}  percent : {{ item.cb_percent }}%</p>
<p>ASK1 : {{ item.ask1 }}  : BUY1 : {{ item.bid1 }}  diff  :  {{ item.diff }}% </p>
</ul>
<br>
<br>
{% endfor %}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Management{% endblock %}

{% block page_content %}
<div class="page-header">
    <a href="{{ url_for('fund.fund_info') }}">fund cb info</a>
    <br>
    <a href="{{ url_for('cb.get_cb_list') }}">cb list</a>
    <br>
    <a href="{{ url_for('jingzhi.gj_info') }}">gj jing zhi</a>
    <br>
    <a href="{{ url_for('jingzhi.hb_info') }}">hb jing zhi</a>
    <br>
    <a href="{{ url_for('realtime.monitor') }}">real time</a>
    <br>
</div>
{% endblock %}

app/templates/jingzhi.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}jing zhi{% endblock %}

{% block page_content %}
{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}

<div>
    <h1>{{ stock_type }} JZ display</h1>
</div>
<div>
    <h2>update jz</h2>
 {{ wtf.quick_form(update_form) }}

</div>
<br>
<br>

<div>
    <h2>jz history</h2>

{{ wtf.quick_form(query_form) }}

</div>

<div class="panel-body">
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                {% for i in labels %}
                <td>{{ i }}</td>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for i in content %}
            <tr>
                {% for j in i %}
                <td>{{ j }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{% endblock %}

app/templates/jsl.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Management{% endblock %}

{% block page_content %}
<div>
    <h1>Convert Bond List</h1>
</div>
<div>
    {{ wtf.quick_form(form) }}

</div>
<div class="panel-body">
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                {% for i in labels %}
                <td>{{ i }}</td>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for i in content %}
            <tr>
                {% for j in i %}
                <td>{{ j }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
            </tbody>

        </table>
        <div>共{{ total }}个</div>
    </div>
</div>
{% endblock %}

app/templates/realtime.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block head %}
{{ super() }}
<script src="/static/jquery-1.12.4.min.js"></script>
<script src="/static/socket.io.js"></script>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        // Use a "/test" namespace.
        // An application can open a connection on multiple namespaces, and
        // Socket.IO will multiplex all those connections on a single
        // physical channel. If you don't care about multiple channels, you
        // can set the namespace to an empty string.
        namespace = '/test';

        // Connect to the Socket.IO server.
        // The connection URL has the following format, relative to the current page:
        //     http[s]://<domain>:<port>[/<namespace>]
        var socket = io(namespace);

        // Event handler for new connections.
        // The callback function is invoked when a connection with the
        // server is established.
        socket.on('connect', function () {
            socket.emit('monitor', {data: 'I\'m connected!'});
        });

        // Event handler for server sent data.
        // The callback function is invoked whenever the server emits data
        // to the client. The data is then displayed in the "Received"
        // section of the page.
        socket.on('my_response', function (msg, cb) {
            console.log('response');
            console.log(msg);
            $('#log').append('<br>' + $('<div/>').text('Received #' + msg.count + ': ' + msg.data).html());

            if (cb)
                cb();
        });

        socket.on('start_response', function (msg, cb) {
            var data = msg['data'];
            var tb_num = msg['num'];
            var tb_name='tb'+tb_num;
            var tb = document.getElementById(tb_name);

            if (tb != null)
                tb.parentNode.removeChild(tb);

            var tb = document.getElementById(tb_name);

            for (var i = 0, len = data.length; i < len; i++) {
                var row = tb.insertRow(tb.rows.length);

                var c0 = row.insertCell(0);
                c0.innerHTML = i;

                var c1 = row.insertCell(1);
                c1.innerHTML = data[i].code;

                var c2 = row.insertCell(2);
                c2.innerHTML = data[i].price;

                var c3 = row.insertCell(3);
                c3.innerHTML = data[i].percent;

                var c4 = row.insertCell(4);
                c4.innerHTML = data[i].name;

                // console.log(data[j]);
            }
        });

        socket.on('stop_response', function (msg, cb) {
            console.log(msg);
        });

        $('form#emit_start').submit(function (event) {
            socket.emit('start_monitor');
            return false;
        });
        $('form#emit_stop').submit(function (event) {
            socket.emit('stop_monitor');
            return false;
        });

    });
</script>
{% endblock %}
{% block title %}Management{% endblock %}
{% block page_content %}

<h1>Realtime monitor</h1>

<form id="emit_start" method="POST" action='#'>
    <input type="submit" value="Start-monitor">
</form>

<br>
<form id="emit_stop" method="POST" action='#'>
    <input type="submit" value="Stop-monitor">
</form>
<br>
<br>
<div>
    <table border="1" id="tb1">
        <tr><td>no</td>
            <td>cdoe</td>
            <td>price</td>
            <td>percent</td>
            <td>name</td>
        </tr>
    </table>

        <table border="1" id="tb2">
        <tr><td>no</td>
            <td>cdoe</td>
            <td>price</td>
            <td>percent</td>
            <td>name</td>
        </tr>
    </table>

        <table border="1" id="tb3">
        <tr><td>no</td>
            <td>cdoe</td>
            <td>price</td>
            <td>percent</td>
            <td>name</td>
        </tr>
    </table>
            <table border="1" id="tb4">
        <tr><td>no</td>
            <td>cdoe</td>
            <td>price</td>
            <td>percent</td>
            <td>name</td>
        </tr>
    </table>
            <table border="1" id="tb5">
        <tr><td>no</td>
            <td>cdoe</td>
            <td>price</td>
            <td>percent</td>
            <td>name</td>
        </tr>
    </table>
</div>
{% endblock %}